# Generated by Django 5.1.7 on 2025-03-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_tag_alter_article_options_remove_article_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scope",
            options={
                "ordering": ["-is_main", "tag__name"],
                "verbose_name": "Связь статьи с разделом",
                "verbose_name_plural": "Связи статей с разделами",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="articles/", verbose_name="Изображение"
            ),
        ),
    ]
